"""
recon.reports.pdf_report — Professional PDF report generator.

Produces a polished, security-consultancy-grade PDF with:
  - Cover page with logo and target info
  - Executive summary with risk score badge
  - Color-coded sections with tables
  - Page numbers and footer
  - CONFIDENTIAL watermark
  - Embedded screenshots
  - Findings and recommendations
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any, Optional

from fpdf import FPDF

from recon import __version__
from recon.config import Config
from recon.utils import safe_filename, timestamp_str

# ──────────────────────────────────────────────────────────────────────────────
# Color scheme
# ──────────────────────────────────────────────────────────────────────────────
COLORS = {
    "bg_dark": (10, 14, 23),
    "bg_surface": (19, 25, 38),
    "accent": (0, 229, 255),
    "success": (0, 230, 118),
    "error": (255, 23, 68),
    "warning": (255, 196, 0),
    "text": (25, 30, 40),
    "text_muted": (85, 95, 110),
    "text_light": (240, 244, 248),
    "text_muted_light": (180, 190, 205),
    "white": (255, 255, 255),
    "black": (0, 0, 0),
    "section_bg": (25, 32, 48),
    "table_header": (30, 40, 60),
    "table_row": (20, 28, 42),
    "table_alt": (15, 22, 35),
}

SEVERITY_COLORS = {
    "Critical": (255, 23, 68),
    "High": (255, 100, 50),
    "Medium": (255, 196, 0),
    "Low": (0, 229, 255),
    "Informational": (150, 150, 150),
}

GRADE_COLORS = {
    "A+": (0, 230, 118),
    "A": (0, 200, 100),
    "B": (100, 200, 0),
    "C": (255, 196, 0),
    "D": (255, 140, 0),
    "F": (255, 23, 68),
}


def _s(text: Any) -> str:
    """Sanitize text to guarantee latin-1 compatibility for legacy FPDF."""
    if text is None:
        return ""
    if not isinstance(text, str):
        text = str(text)
    replacements = {
        "—": "-",
        "–": "-",
        "“": '"',
        "”": '"',
        "‘": "'",
        "’": "'",
        "•": "*",
        "✓": "[OK]",
        "✗": "[X]",
        "▶": ">",
        "🛡️": "",
        "🛡": "",
        "◉": "*",
        "●": "*",
        "○": "o",
        "\u2014": "-",
        "\u2013": "-",
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    return text.encode("latin-1", errors="replace").decode("latin-1")


class ReconPDF(FPDF):
    """Custom PDF class with header/footer and watermark."""

    def __init__(self, target: str = "") -> None:
        super().__init__()
        self.target = target
        self._page_has_watermark = False

    def cell(self, w, h=0, txt="", border=0, ln=0, align="", fill=0, link=""):
        return super().cell(w, h, _s(txt), border=border, ln=ln, align=align, fill=fill, link=link)

    def multi_cell(self, w, h, txt="", border=0, align="J", fill=0, split_only=False):
        return super().multi_cell(w, h, _s(txt), border=border, align=align, fill=fill, split_only=split_only)

    def header(self) -> None:
        if self.page_no() > 1:
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(*COLORS["text_muted"])
            self.cell(0, 6, f"Reconnaissance Report — {self.target}", align="L", ln=0)
            self.cell(0, 6, "CONFIDENTIAL", align="R", ln=1)
            self.set_draw_color(*COLORS["accent"])
            self.line(10, 16, 200, 16)
            self.ln(4)

    def footer(self) -> None:
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*COLORS["text_muted"])
        self.cell(0, 10, f"Generated by Automatic Recon Tool v{__version__}", align="L")
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="R")


def _add_cover_page(pdf: ReconPDF, scan: Any, logo_path: Optional[str]) -> None:
    """Add a professional cover page."""
    pdf.add_page()
    pdf.set_fill_color(*COLORS["bg_dark"])
    pdf.rect(0, 0, 210, 297, "F")

    # Logo
    if logo_path and os.path.exists(logo_path):
        try:
            pdf.image(logo_path, x=55, y=30, w=100)
        except Exception:
            pass

    # Title
    pdf.set_y(110)
    pdf.set_font("Helvetica", "B", 28)
    pdf.set_text_color(*COLORS["accent"])
    pdf.cell(0, 15, "RECONNAISSANCE", align="C", ln=1)
    pdf.cell(0, 15, "REPORT", align="C", ln=1)

    # Divider
    pdf.ln(5)
    pdf.set_draw_color(*COLORS["accent"])
    pdf.set_line_width(0.8)
    pdf.line(60, pdf.get_y(), 150, pdf.get_y())
    pdf.ln(10)

    # Target info
    pdf.set_font("Helvetica", "", 14)
    pdf.set_text_color(*COLORS["text_light"])
    pdf.cell(0, 10, f"Target: {scan.target}", align="C", ln=1)
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(*COLORS["text_muted_light"])
    pdf.cell(0, 8, f"Scan Date: {scan.start_time}", align="C", ln=1)
    pdf.cell(0, 8, f"Duration: {scan.total_duration:.1f} seconds", align="C", ln=1)

    # Score badge
    if scan.score:
        pdf.ln(15)
        grade = scan.score.grade
        color = GRADE_COLORS.get(grade, COLORS["text_light"])
        pdf.set_font("Helvetica", "B", 48)
        pdf.set_text_color(*color)
        pdf.cell(0, 25, grade, align="C", ln=1)
        pdf.set_font("Helvetica", "", 14)
        pdf.cell(0, 10, f"Security Score: {scan.score.score}/100", align="C", ln=1)
        pdf.set_text_color(*SEVERITY_COLORS.get(scan.score.risk_level, COLORS["text_light"]))
        pdf.cell(0, 8, f"Risk Level: {scan.score.risk_level}", align="C", ln=1)

    # Confidential notice
    pdf.set_y(265)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(*COLORS["text_muted_light"])
    pdf.cell(0, 5, "CONFIDENTIAL — For authorized personnel only", align="C", ln=1)
    pdf.cell(0, 5, f"Automatic Recon Tool v{__version__}", align="C", ln=1)


def _section_title(pdf: ReconPDF, title: str) -> None:
    """Add a styled section title."""
    pdf.ln(6)
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(*COLORS["accent"])
    pdf.cell(0, 10, title, ln=1)
    pdf.set_draw_color(*COLORS["accent"])
    pdf.set_line_width(0.4)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)


def _key_value(pdf: ReconPDF, key: str, value: str, indent: int = 10) -> None:
    """Add a key-value pair."""
    pdf.set_x(indent)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*COLORS["text_muted"])
    key_width = max(pdf.get_string_width(key + ": ") + 2, 40)
    pdf.cell(key_width, 6, f"{key}:", ln=0)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*COLORS["text"])
    pdf.multi_cell(0, 6, str(value) if value else "N/A")


def _add_table(
    pdf: ReconPDF,
    headers: list[str],
    rows: list[list[str]],
    col_widths: Optional[list[int]] = None,
) -> None:
    """Add a styled table."""
    if not rows:
        return

    n = len(headers)
    if col_widths is None:
        w = 190 // n
        col_widths = [w] * n
        # Adjust last column to fill remaining space
        col_widths[-1] = 190 - sum(col_widths[:-1])

    # Header
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(*COLORS["table_header"])
    pdf.set_text_color(*COLORS["accent"])
    for i, h in enumerate(headers):
        pdf.cell(col_widths[i], 7, h, border=0, fill=True)
    pdf.ln()

    # Rows
    pdf.set_font("Helvetica", "", 9)
    for idx, row in enumerate(rows):
        bg = COLORS["table_row"] if idx % 2 == 0 else COLORS["table_alt"]
        pdf.set_fill_color(*bg)
        pdf.set_text_color(*COLORS["text_light"])
        for i, cell in enumerate(row):
            text = str(cell)[:50]  # Truncate long values
            pdf.cell(col_widths[i], 6, text, border=0, fill=True)
        pdf.ln()


def generate(scan: Any, config: Optional[Config] = None) -> str:
    """Generate a professional PDF report.

    Args:
        scan: ScanResult from the engine.
        config: Optional Config for output directory and logo path.

    Returns:
        Path to the saved PDF file.
    """
    cfg = config or Config()
    pdf = ReconPDF(target=scan.target)
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)

    # ── Cover Page ────────────────────────────────────────────────────
    logo = str(cfg.logo_path) if cfg.logo_path.exists() else None
    _add_cover_page(pdf, scan, logo)

    # ── Executive Summary ─────────────────────────────────────────────
    pdf.add_page()
    _section_title(pdf, "EXECUTIVE SUMMARY")
    if scan.summary:
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(*COLORS["text"])
        for para in scan.summary.split("\n\n"):
            pdf.multi_cell(0, 5, para)
            pdf.ln(3)

    # ── Security Findings ─────────────────────────────────────────────
    if scan.score and scan.score.findings:
        _section_title(pdf, "SECURITY FINDINGS")

        rows = []
        for f in scan.score.findings:
            rows.append([f.severity, f.title, f.category, str(f.points_deducted)])
        _add_table(pdf, ["Severity", "Finding", "Category", "Pts"], rows, [25, 90, 45, 20])

    # ── Network Information ───────────────────────────────────────────
    geo = scan.results.get("geo")
    if geo and getattr(geo, "success", False):
        _section_title(pdf, "NETWORK INFORMATION")
        _key_value(pdf, "IP Address", geo.ip)
        _key_value(pdf, "Location", f"{geo.city}, {geo.region}, {geo.country}")
        _key_value(pdf, "ISP", geo.isp)
        _key_value(pdf, "Organization", geo.org)
        _key_value(pdf, "ASN", geo.as_number)

    # ── WHOIS ─────────────────────────────────────────────────────────
    w = scan.results.get("whois")
    if w and getattr(w, "success", False):
        _section_title(pdf, "WHOIS INFORMATION")
        _key_value(pdf, "Domain", w.domain_name)
        _key_value(pdf, "Registrar", w.registrar)
        _key_value(pdf, "Created", w.creation_date)
        _key_value(pdf, "Expires", w.expiration_date)
        _key_value(pdf, "Name Servers", ", ".join(w.name_servers) if w.name_servers else "N/A")

    # ── DNS Records ───────────────────────────────────────────────────
    dns = scan.results.get("dns")
    if dns and getattr(dns, "success", False):
        _section_title(pdf, "DNS RECORDS")
        rows = []
        for rtype, rec in dns.records.items():
            vals = ", ".join(rec.values) if rec.values else "None"
            ttl = str(rec.ttl) if rec.ttl else "-"
            rows.append([rtype, vals[:80], ttl])
        _add_table(pdf, ["Type", "Values", "TTL"], rows, [20, 150, 20])

        pdf.ln(3)
        _key_value(pdf, "SPF", dns.spf or "Not found")
        _key_value(pdf, "DMARC", dns.dmarc or "Not found")
        _key_value(pdf, "DNSSEC", "Enabled" if dns.has_dnssec else "Not enabled")

    # ── HTTP Analysis ─────────────────────────────────────────────────
    http = scan.results.get("http")
    if http and getattr(http, "success", False):
        _section_title(pdf, "HTTP SECURITY HEADERS")
        rows = []
        for header, value in http.security_headers.items():
            status = "Present" if value else "MISSING"
            rows.append([header, status, (value or "-")[:60]])
        _add_table(pdf, ["Header", "Status", "Value"], rows, [60, 25, 105])

    # ── SSL/TLS ───────────────────────────────────────────────────────
    ssl_r = scan.results.get("ssl")
    if ssl_r and getattr(ssl_r, "success", False):
        _section_title(pdf, "SSL/TLS CERTIFICATE")
        _key_value(pdf, "Subject", ssl_r.subject)
        _key_value(pdf, "Issuer", ssl_r.issuer)
        _key_value(pdf, "TLS Version", ssl_r.tls_version)
        _key_value(pdf, "Cipher Suite", ssl_r.cipher_suite)
        _key_value(pdf, "Cert Grade", ssl_r.grade)
        _key_value(pdf, "Valid Until", ssl_r.not_after)
        _key_value(pdf, "Days Remaining", str(ssl_r.days_until_expiry))
        _key_value(pdf, "Signature", ssl_r.signature_algorithm or "N/A")
        if ssl_r.san:
            _key_value(pdf, "SAN", ", ".join(ssl_r.san[:5]))

    # ── Technology Stack ──────────────────────────────────────────────
    tech = scan.results.get("tech")
    if tech and getattr(tech, "success", False):
        _section_title(pdf, "TECHNOLOGY STACK")
        rows = []
        for category, techs in tech.categories.items():
            rows.append([category, ", ".join(techs)])
        _add_table(pdf, ["Category", "Technologies"], rows, [50, 140])

    # ── Admin Panels ──────────────────────────────────────────────────
    admin = scan.results.get("admin")
    if admin and getattr(admin, "success", False) and admin.findings:
        _section_title(pdf, "ADMIN PANEL DISCOVERY")
        rows = []
        for f in admin.findings[:25]:
            rows.append([f.classification, f.url, str(f.status_code)])
        _add_table(pdf, ["Status", "URL", "Code"], rows, [35, 135, 20])

    # ── Subdomains ────────────────────────────────────────────────────
    subs = scan.results.get("subdomains")
    if subs and getattr(subs, "success", False) and subs.subdomains:
        _section_title(pdf, "SUBDOMAIN ENUMERATION")
        _key_value(pdf, "Total Found", str(subs.total_count))
        _key_value(pdf, "Sources", ", ".join(subs.sources_used))
        pdf.ln(3)
        rows = [[s] for s in subs.subdomains[:40]]
        _add_table(pdf, ["Subdomain"], rows, [190])

    # ── Shodan ────────────────────────────────────────────────────────
    shodan = scan.results.get("shodan")
    if shodan and getattr(shodan, "success", False):
        _section_title(pdf, "SHODAN INTELLIGENCE")
        _key_value(pdf, "IP", shodan.ip)
        _key_value(pdf, "Organization", shodan.org)
        _key_value(pdf, "ISP", shodan.isp)
        _key_value(pdf, "ASN", shodan.asn)
        _key_value(pdf, "OS", shodan.os)
        if shodan.ports:
            pdf.ln(3)
            rows = []
            for p in shodan.ports[:15]:
                product = p.product or "-"
                version = p.version or "-"
                rows.append([str(p.port), p.transport, product, version])
            _add_table(pdf, ["Port", "Proto", "Product", "Version"], rows, [25, 25, 80, 60])
        if shodan.vulns:
            pdf.ln(3)
            rows = [[v] for v in shodan.vulns[:20]]
            _add_table(pdf, ["Known CVE"], rows, [190])

    # ── Screenshots ───────────────────────────────────────────────────
    screenshot = scan.results.get("screenshot")
    if screenshot and getattr(screenshot, "success", False):
        _section_title(pdf, "SCREENSHOTS")
        for label, path in [
            ("Desktop", getattr(screenshot, "desktop_path", None)),
            ("Mobile", getattr(screenshot, "mobile_path", None)),
            ("Full Page", getattr(screenshot, "fullpage_path", None)),
        ]:
            if path and os.path.exists(path):
                pdf.set_font("Helvetica", "B", 10)
                pdf.set_text_color(*COLORS["text_muted"])
                pdf.cell(0, 8, f"{label} Screenshot:", ln=1)
                try:
                    # Fit to page width
                    pdf.image(path, x=10, w=190)
                    pdf.ln(5)
                except Exception:
                    pdf.set_text_color(*COLORS["error"])
                    pdf.cell(0, 6, f"Failed to embed {label} screenshot", ln=1)

    # ── Recommendations ───────────────────────────────────────────────
    if scan.score and scan.score.findings:
        pdf.add_page()
        _section_title(pdf, "RECOMMENDATIONS")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(*COLORS["text"])

        recommendations = []
        for f in scan.score.findings:
            if f.severity in ("Critical", "High"):
                recommendations.append(f"[{f.severity}] Address: {f.title} — {f.description}")
            elif f.severity == "Medium":
                recommendations.append(f"[{f.severity}] Consider: {f.title}")

        if recommendations:
            for i, rec in enumerate(recommendations, 1):
                pdf.multi_cell(0, 5, f"{i}. {rec}")
                pdf.ln(2)
        else:
            pdf.cell(0, 8, "No critical or high-severity findings to address.", ln=1)

    # ── Save ──────────────────────────────────────────────────────────
    filename = cfg.documents_dir / f"{safe_filename(scan.target)}_report_{timestamp_str()}.pdf"
    filename.parent.mkdir(parents=True, exist_ok=True)
    pdf.output(str(filename))

    return str(filename)
